services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
  web:
    build: ./app
    command: /bin/sh -c "/app/startup.sh"
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      db:
        condition: service_healthy
volumes:
  db:
    driver: local