services:
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
    - db:/var/lib/postgresql/data
  web:
    build: ./app
    command: /bin/sh -c "/app/startup.sh"
    volumes:
      - ./app/:/usr/src/app/
    ports:
    - 8000:8000
    depends_on:
      - db
volumes:
  db:
    driver: local