name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.7'
    - name: Install Dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PSQL
      uses: ikalnytskyi/action-setup-postgres@v7
      id: postgres
    - name: Setup PSQL user
      run: |
        psql postgresql://postgres:postgres@localhost:5432/postgres -c "CREATE USER task_admin WITH PASSWORD 'admin'"
        psql service=postgres -c "CREATE USER task_admin WITH PASSWORD 'admin'"
      env:
        PGSERVICE: postgres
    - name: Run Tests
      working-directory: ./app
      run: |
        pytest
